### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by naaando** [joseildocruz/Inforam#1]
Não seria melhor usar as notificações nativas do sistema ao invés do yad?

**Comment by joseildocruz** [comment]
Certamente sim. Mas no meu caso prefiro o yad porque, além de criar o script de acordo com minha necessidade, é prático e eficiênte. No Ubuntu as notificações só aparecem quando realmente está no fim, então uso o script para configurar a %. 
O bom de tudo é porque temos muitas escolhas e sempre uma delas se adequa a nossa necessidade.
